name: Build & Publish Profile Controller Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/profile-controller/**
      - releasing/version/VERSION

env:
  ARCH: linux/ppc64le,linux/amd64
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/dnsmasq
  IMG: ${{ github.actor }}/dnsmasq

jobs:
  push_to_registry:
    name: Build & Push Docker image to GHCR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'
    
    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push multi-arch docker image
      run: |
        cd components/profile-controller
        make docker-build-push-multi-arch

    - name: Build and push latest multi-arch docker image
      if: github.ref == 'refs/heads/master'
      run: |
        export TAG=latest
        cd components/profile-controller
        make docker-build-push-multi-arch

    - name: Build and push multi-arch docker image on Version change
      id: version
      if: steps.filter.outputs.version == 'true'
      run: |
        export TAG=$(cat releasing/version/VERSION)
        cd components/profile-controller
        make docker-build-push-multi-arch
